#!/bin/bash

echo "Hello World"
echo $(which neqn) # .... (i)
cat $(which neqn) 

# (i): which is used to find the location of the bash file neqn; then the echo command is used to
#      print the location to the screen