#!/bin/sh

# Adapted (changed name and added comments to this file) a script written by: 
# Westley Weimer, Wed Mar 19 17:58:09 EDT 2008

# USAGE: splitpdf [input.pdf] [first_page] [last_page] [output.pdf] 

# Example: splitpdf big_file.pdf 10 20 pages_ten_to_twenty.pdf

if [ $# -lt 4 ] 
then
        echo "Usage: splitpdf input.pdf first_page last_page output.pdf"
        exit 1
fi

# ghostscript (gs) will do PDF splitting for you, it's just not obvious and the required defines are
# not listed in the manual page. 

gs -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$4" -dFirstPage=$2 -dLastPage=$3 -sDEVICE=pdfwrite "$1"


# Recommended changes:
# * Change the name of this utility to "extractpagesfrompdf"
# * Increase capability to add more ranges, for example: 
#   a line such as "extractpagesfrompdf input.pdf 1 5 10 11 20 30 output.pdf" would create a new 
#   file that contains pages 1 to 5, 10 to 11, and 20 to 30
#   - it would be even better to write the command like this:
#     "extractpagesfrompdf input.pdf 1-5, 10-11, 20-30 output.pdf"
